### ISSUE TITLE
Save and Continue Button on Create Profile Page Throws Error 

### ISSUE THREAD

**Issue by claytical** [gabycostales/firefighterApp#1]
FatalThrowableError in 522b316538c1263361daf84ef2b3b91128fdebe0.php line 51:
Fatal error: Call to a member function format() on string

ErrorException in 522b316538c1263361daf84ef2b3b91128fdebe0.php line 51:
Fatal error: Call to a member function format() on string (View: /home/forge/default/resources/views/profile/step1.blade.php)

**Comment by gabycostales** [comment]
This should be resolved now - add check for birthdate existence to view and redirect to edit route/action if  user has an existing profile already but navigates /profile/create. Let me know if you guys are able to create profiles now

**Comment by smollydominick** [comment]
I'm getting an error still when trying to create a profile. I filled out the first section...

<img width="998" alt="screen shot 2016-05-02 at 6 36 49 pm" src="https://cloud.githubusercontent.com/assets/16679132/14970313/de2230e6-1095-11e6-8437-f9ad0d35fd1c.png">

...pressed Save & Continue, and I got the following error message:

<img width="1280" alt="screen shot 2016-05-02 at 6 36 08 pm" src="https://cloud.githubusercontent.com/assets/16679132/14970311/de1bc7ba-1095-11e6-8e81-ba458d8997fd.png">
<img width="1280" alt="screen shot 2016-05-02 at 6 36 23 pm" src="https://cloud.githubusercontent.com/assets/16679132/14970310/de190fa2-1095-11e6-9340-e8f3acda4cc3.png">
<img width="1279" alt="screen shot 2016-05-02 at 6 36 33 pm" src="https://cloud.githubusercontent.com/assets/16679132/14970312/de20c288-1095-11e6-82f8-b2cd4798a20a.png">

**Comment by gabycostales** [comment]
Removed the date mutators from the Model and parsing them on the Controller side so this should no longer be a problem
